spring:
  config:
    activate:
      on-profile: test
  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    redis:
      host: redis-container
      port: 6379